In [113]:
import pandas as pd
from sklearn import model_selection, preprocessing
from sklearn.ensemble import RandomForestClassifier
from matplotlib import pyplot as plt
%matplotlib inline

In [127]:
train = pd.read_csv("train.csv")

In [128]:
labels = pd.read_csv("labels.csv")

In [129]:
train

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,0,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,0,...,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
5,9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,0,...,per bucket,salty,salty,enough,enough,other,other,unknown,communal standpipe multiple,communal standpipe
6,19816,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,0,...,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
7,54551,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,0,...,unknown,milky,milky,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
8,53934,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,0,...,never pay,salty,salty,seasonal,seasonal,machine dbh,borehole,groundwater,hand pump,hand pump
9,46144,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,0,...,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
10,49056,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,0,...,never pay,salty,salty,enough,enough,machine dbh,borehole,groundwater,other,other
11,50409,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,0,...,on failure,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
12,36957,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,0,...,other,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
13,50495,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
14,53752,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,0,...,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
15,61848,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,0,...,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
16,48451,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,0,...,monthly,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe
17,58155,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,0,...,on failure,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe
18,34169,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,0,...,never pay,milky,milky,insufficient,insufficient,spring,spring,groundwater,other,other
19,18274,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
20,48375,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,none,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
21,6091,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,0,...,unknown,unknown,unknown,unknown,unknown,shallow well,shallow well,groundwater,hand pump,hand pump
22,58500,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,0,...,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
23,37862,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,0,...,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
24,51058,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,0,...,unknown,soft,good,enough,enough,spring,spring,groundwater,improved spring,improved spring
25,22308,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,0,...,unknown,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
26,55012,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,0,...,monthly,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
27,20145,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,0,...,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
28,19685,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,0,...,monthly,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
29,69124,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59370,14796,200.0,2013-01-29,NaN,1154,NaN,30.058731,-4.902633e+00,Village Office,0,...,monthly,unknown,unknown,unknown,unknown,unknown,other,unknown,other,other
59371,20387,0.0,2012-10-09,Netherlands,0,DWE,33.586406,-3.040369e+00,Ushirika,0,...,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
59372,29940,0.0,2012-10-31,Tlc,0,TLC,32.058548,-5.052101e+00,Kwa Mzee Kamanya,0,...,per bucket,salty,salty,insufficient,insufficient,shallow well,shallow well,groundwater,other,other
59373,15233,5000.0,2013-01-30,Rudep,1137,Distri,32.125024,-6.784358e+00,Kwa Kadiega,0,...,annually,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59374,49651,0.0,2012-10-29,Rwssp,0,DWE,0.000000,-2.000000e-08,Nguvu Kazi,0,...,other,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
59375,50998,40000.0,2011-08-03,Government Of Tanzania,54,DWE,39.046942,-5.061494e+00,Sekondari,0,...,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59376,34716,0.0,2013-02-03,NaN,1581,NaN,34.821039,-5.076258e+00,Nasingo,0,...,unknown,unknown,unknown,dry,dry,shallow well,shallow well,groundwater,other,other
59377,43986,0.0,2012-10-23,Government Of Tanzania,0,Government,33.437012,-4.423594e+00,Fpct,0,...,never pay,soft,good,insufficient,insufficient,dam,dam,surface,communal standpipe multiple,communal standpipe
59378,38067,500.0,2011-03-21,Rc,2101,ACRA,34.620387,-9.358405e+00,Michael Msigwa,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59379,58255,0.0,2011-07-13,Do,0,DO,31.613284,-1.820226e+00,Coffee Plantati,0,...,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59380,30647,6000.0,2011-03-14,Roman,1439,Roman,34.942101,-9.849198e+00,none,0,...,annually,soft,good,dry,dry,spring,spring,groundwater,communal standpipe,communal standpipe
59381,67885,0.0,2011-03-16,Mkinga Distric Coun,0,DWE,38.835001,-4.880204e+00,Mijohoroni,0,...,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
59382,47002,6.0,2013-08-03,Ces(gmbh),1383,DWE,37.454759,-3.323599e+00,Kwa Luka Msaki,0,...,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59383,44616,0.0,2013-01-19,World Bank,11,World bank,39.626009,-1.005750e+01,Shuleni,0,...,unknown,soft,good,enough,enough,rainwater harvesting,rainwater harvesting,surface,hand pump,hand pump
59384,72148,0.0,2011-07-10,Concern,0,CONCERN,30.667805,-2.483710e+00,Chamkube,0,...,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
59385,34473,500.0,2012-11-03,Jaica,1327,JAICA CO,33.951681,-2.021854e+00,Kwa Marunda,0,...,monthly,salty,salty,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59386,34952,0.0,2011-08-22,Adb,1786,DWE,31.738789,-8.532013e+00,Shule Ya Sekondari Katazi,0,...,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59387,26640,100.0,2013-03-12,0,25,0,39.176480,-6.957098e+00,Kwa Maliba,0,...,per bucket,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
59388,72559,0.0,2013-01-29,Kidep,1414,DWE,30.692400,-3.593827e+00,Kwa Philipo Kibeba,0,...,unknown,soft,good,insufficient,insufficient,spring,spring,groundwater,improved spring,improved spring
59389,30410,0.0,2011-08-06,Co,783,DWE,30.646486,-7.365418e+00,Sekondari,0,...,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59390,13677,0.0,2011-08-04,Rudep,1715,DWE,31.370848,-8.258160e+00,Kwa Mzee Atanas,0,...,never pay,soft,good,insufficient,insufficient,machine dbh,borehole,groundwater,hand pump,hand pump
59391,44885,0.0,2013-08-03,Government Of Tanzania,540,Government,38.044070,-4.272218e+00,Kwa,0,...,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59392,40607,0.0,2011-04-15,Government Of Tanzania,0,Government,33.009440,-8.520888e+00,Benard Charles,0,...,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59393,48348,0.0,2012-10-27,Private,0,Private,33.866852,-4.287410e+00,Kwa Peter,0,...,per bucket,soft,good,insufficient,insufficient,dam,dam,surface,other,other
59394,11164,500.0,2011-03-09,World Bank,351,ML appro,37.634053,-6.124830e+00,Chimeredya,0,...,monthly,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
59395,60739,10.0,2013-05-03,Germany Republi,1210,CES,37.169807,-3.253847e+00,Area Three Namba 27,0,...,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59396,27263,4700.0,2011-05-07,Cefa-njombe,1212,Cefa,35.249991,-9.070629e+00,Kwa Yahona Kuvala,0,...,annually,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59397,37057,0.0,2011-04-11,NaN,0,NaN,34.017087,-8.750434e+00,Mashine,0,...,monthly,fluoride,fluoride,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59398,31282,0.0,2011-03-08,Malec,0,Musa,35.861315,-6.378573e+00,Mshoro,0,...,never pay,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
59399,26348,0.0,2011-03-23,World Bank,191,World,38.104048,-6.747464e+00,Kwa Mzee Lugawa,0,...,on failure,salty,salty,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump

In [48]:
labels

          id             status_group
0      69572               functional
1       8776               functional
2      34310               functional
3      67743           non functional
4      19728               functional
5       9944               functional
6      19816           non functional
7      54551           non functional
8      53934           non functional
9      46144               functional
10     49056               functional
11     50409               functional
12     36957               functional
13     50495               functional
14     53752               functional
15     61848               functional
16     48451           non functional
17     58155           non functional
18     34169  functional needs repair
19     18274               functional
20     48375               functional
21      6091               functional
22     58500  functional needs repair
23     37862               functional
24     51058               functional
25     22308  functional needs repair
26     55012               functional
27     20145               functional
28     19685           non functional
29     69124               functional
...      ...                      ...
59370  14796               functional
59371  20387           non functional
59372  29940           non functional
59373  15233               functional
59374  49651               functional
59375  50998               functional
59376  34716           non functional
59377  43986           non functional
59378  38067               functional
59379  58255               functional
59380  30647           non functional
59381  67885           non functional
59382  47002           non functional
59383  44616               functional
59384  72148           non functional
59385  34473               functional
59386  34952               functional
59387  26640               functional
59388  72559               functional
59389  30410               functional
59390  13677               functional
59391  44885           non functional
59392  40607           non functional
59393  48348               functional
59394  11164           non functional
59395  60739               functional
59396  27263               functional
59397  37057               functional
59398  31282               functional
59399  26348               functional

[59400 rows x 2 columns]

In [69]:
train.describe()

,id,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,construction_year
count,48651.000000,48651.000000,48651.000000,48651.000000,4.865100e+04,48651.000000,48651.000000,48651.000000,48651.000000,48651.000000
mean,37123.666461,357.728195,696.307948,34.231358,-5.703496e+00,0.548026,14.691928,5.733983,175.374648,1332.837557
std,21434.789000,2818.035843,698.803652,6.308931,2.860400e+00,13.241609,17.211805,9.668654,470.986147,940.738023
min,2.000000,0.000000,-90.000000,0.000000,-1.164944e+01,0.000000,1.000000,0.000000,0.000000,0.000000
25%,18563.500000,0.000000,0.000000,33.050798,-8.219734e+00,0.000000,5.000000,2.000000,0.000000,0.000000
50%,37067.000000,0.000000,451.000000,35.265198,-5.018264e+00,0.000000,12.000000,3.000000,30.000000,1986.000000
75%,55646.500000,50.000000,1332.000000,37.339128,-3.337892e+00,0.000000,17.000000,5.000000,200.000000,2005.000000
max,74247.000000,250000.000000,2770.000000,40.323402,-2.000000e-08,1776.000000,99.000000,80.000000,30500.000000,2013.000000

In [45]:
labels.describe()

                 id
count  59400.000000
mean   37115.131768
std    21453.128371
min        0.000000
25%    18519.750000
50%    37061.500000
75%    55656.500000
max    74247.000000

In [130]:
train = train.merge(labels, on = "id", how = "inner")

Finding features with null values

In [131]:
train.apply(lambda x : sum(x.isnull()), axis = 0)

id                           0
amount_tsh                   0
date_recorded                0
funder                    3635
gps_height                   0
installer                 3655
longitude                    0
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting            3334
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                    3056
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
status_group                 0
dtype: int64

Deleting null rows

In [132]:
train.dropna(subset = ['funder', 'installer', 'scheme_management', 'permit'], inplace = True)

Filling null rows in 'public_meeting' column

In [133]:
train.public_meeting = train.public_meeting.fillna('na')

In [134]:
train['recorded_by'].value_counts()

GeoData Consultants Ltd    51281
Name: recorded_by, dtype: int64

As all the values in this column are same, it doesn't add anything unique for the prediction. We drop it.

In [135]:
train=train.drop(['recorded_by'],axis=1)

In [136]:
train[['waterpoint_type_group', 'waterpoint_type']]

      waterpoint_type_group              waterpoint_type
0        communal standpipe           communal standpipe
1        communal standpipe           communal standpipe
2        communal standpipe  communal standpipe multiple
3        communal standpipe  communal standpipe multiple
5        communal standpipe  communal standpipe multiple
6                 hand pump                    hand pump
8                 hand pump                    hand pump
10                    other                        other
11                hand pump                    hand pump
12                hand pump                    hand pump
13       communal standpipe           communal standpipe
14                hand pump                    hand pump
15                hand pump                    hand pump
16       communal standpipe           communal standpipe
17       communal standpipe           communal standpipe
19       communal standpipe           communal standpipe
20       communal standpipe           communal standpipe
21                hand pump                    hand pump
22       communal standpipe           communal standpipe
23       communal standpipe           communal standpipe
24          improved spring              improved spring
25       communal standpipe           communal standpipe
26                hand pump                    hand pump
28       communal standpipe           communal standpipe
29       communal standpipe           communal standpipe
30                hand pump                    hand pump
31       communal standpipe           communal standpipe
32                    other                        other
33       communal standpipe           communal standpipe
36       communal standpipe           communal standpipe
...                     ...                          ...
59365    communal standpipe           communal standpipe
59367    communal standpipe           communal standpipe
59368    communal standpipe           communal standpipe
59369    communal standpipe           communal standpipe
59371             hand pump                    hand pump
59372                 other                        other
59373             hand pump                    hand pump
59374             hand pump                    hand pump
59375    communal standpipe           communal standpipe
59377    communal standpipe  communal standpipe multiple
59378    communal standpipe           communal standpipe
59379    communal standpipe           communal standpipe
59380    communal standpipe           communal standpipe
59381    communal standpipe           communal standpipe
59382    communal standpipe           communal standpipe
59384    communal standpipe           communal standpipe
59385             hand pump                    hand pump
59386             hand pump                    hand pump
59387    communal standpipe           communal standpipe
59388       improved spring              improved spring
59389             hand pump                    hand pump
59390             hand pump                    hand pump
59391    communal standpipe           communal standpipe
59392    communal standpipe           communal standpipe
59393                 other                        other
59394    communal standpipe           communal standpipe
59395    communal standpipe           communal standpipe
59396    communal standpipe           communal standpipe
59398             hand pump                    hand pump
59399             hand pump                    hand pump

[51281 rows x 2 columns]

In [137]:
train['waterpoint_type'].value_counts()

communal standpipe             25055
hand pump                      14607
communal standpipe multiple     5944
other                           4929
improved spring                  657
cattle trough                     83
dam                                6
Name: waterpoint_type, dtype: int64

In [138]:
train['waterpoint_type_group'].value_counts()

communal standpipe    30999
hand pump             14607
other                  4929
improved spring         657
cattle trough            83
dam                       6
Name: waterpoint_type_group, dtype: int64

We merge the two dropping one as as data 'communal standpipe' and 'communal standpipe multiple' differ.

In [139]:
train=train.drop(['waterpoint_type'],axis=1)

We do the same with 'quantity' and 'quantity_group' due to following observation.

In [140]:
train[['quantity', 'quantity_group']]

           quantity quantity_group
0            enough         enough
1      insufficient   insufficient
2            enough         enough
3               dry            dry
5            enough         enough
6            enough         enough
8          seasonal       seasonal
10           enough         enough
11     insufficient   insufficient
12           enough         enough
13           enough         enough
14           enough         enough
15           enough         enough
16              dry            dry
17              dry            dry
19           enough         enough
20           enough         enough
21          unknown        unknown
22           enough         enough
23           enough         enough
24           enough         enough
25           enough         enough
26           enough         enough
28     insufficient   insufficient
29           enough         enough
30     insufficient   insufficient
31           enough         enough
32     insufficient   insufficient
33         seasonal       seasonal
36              dry            dry
...             ...            ...
59365        enough         enough
59367        enough         enough
59368        enough         enough
59369        enough         enough
59371        enough         enough
59372  insufficient   insufficient
59373        enough         enough
59374        enough         enough
59375        enough         enough
59377  insufficient   insufficient
59378        enough         enough
59379        enough         enough
59380           dry            dry
59381  insufficient   insufficient
59382        enough         enough
59384  insufficient   insufficient
59385        enough         enough
59386        enough         enough
59387        enough         enough
59388  insufficient   insufficient
59389        enough         enough
59390  insufficient   insufficient
59391        enough         enough
59392        enough         enough
59393  insufficient   insufficient
59394        enough         enough
59395        enough         enough
59396        enough         enough
59398  insufficient   insufficient
59399        enough         enough

[51281 rows x 2 columns]

In [141]:
train['quantity'].value_counts()

enough          30076
insufficient    12304
dry              5492
seasonal         3034
unknown           375
Name: quantity, dtype: int64

In [142]:
train['quantity_group'].value_counts()

enough          30076
insufficient    12304
dry              5492
seasonal         3034
unknown           375
Name: quantity_group, dtype: int64

We do the same with 'payment' and 'payment_type' due to following observation.

In [143]:
train[['payment', 'payment_type']]

                     payment payment_type
0               pay annually     annually
1                  never pay    never pay
2             pay per bucket   per bucket
3                  never pay    never pay
5             pay per bucket   per bucket
6                  never pay    never pay
8                  never pay    never pay
10                 never pay    never pay
11     pay when scheme fails   on failure
12                     other        other
13               pay monthly      monthly
14                 never pay    never pay
15                 never pay    never pay
16               pay monthly      monthly
17     pay when scheme fails   on failure
19              pay annually     annually
20               pay monthly      monthly
21                   unknown      unknown
22                 never pay    never pay
23               pay monthly      monthly
24                   unknown      unknown
25                   unknown      unknown
26               pay monthly      monthly
28               pay monthly      monthly
29               pay monthly      monthly
30                 never pay    never pay
31            pay per bucket   per bucket
32                 never pay    never pay
33     pay when scheme fails   on failure
36                 never pay    never pay
...                      ...          ...
59365  pay when scheme fails   on failure
59367           pay annually     annually
59368         pay per bucket   per bucket
59369  pay when scheme fails   on failure
59371              never pay    never pay
59372         pay per bucket   per bucket
59373           pay annually     annually
59374                  other        other
59375            pay monthly      monthly
59377              never pay    never pay
59378            pay monthly      monthly
59379              never pay    never pay
59380           pay annually     annually
59381              never pay    never pay
59382         pay per bucket   per bucket
59384              never pay    never pay
59385            pay monthly      monthly
59386              never pay    never pay
59387         pay per bucket   per bucket
59388                unknown      unknown
59389              never pay    never pay
59390              never pay    never pay
59391              never pay    never pay
59392              never pay    never pay
59393         pay per bucket   per bucket
59394            pay monthly      monthly
59395         pay per bucket   per bucket
59396           pay annually     annually
59398              never pay    never pay
59399  pay when scheme fails   on failure

[51281 rows x 2 columns]

In [144]:
train['payment'].value_counts()

never pay                21360
pay per bucket            8500
pay monthly               7614
unknown                   5705
pay when scheme fails     3653
pay annually              3484
other                      965
Name: payment, dtype: int64

In [145]:
train['payment_type'].value_counts()

never pay     21360
per bucket     8500
monthly        7614
unknown        5705
on failure     3653
annually       3484
other           965
Name: payment_type, dtype: int64

Data is same but rephrased. So, safe to drop one of the features.

In [146]:
train=train.drop(['payment'],axis=1)

Checking the correlation of dataset

In [74]:
train.corr()

,id,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,public_meeting,construction_year
id,1.000000,-0.007463,-0.006931,-0.005045,0.004229,-0.002469,-0.002713,-0.004486,-0.004761,0.004720,-0.004744
amount_tsh,-0.007463,1.000000,0.089882,0.022620,-0.069686,0.002081,-0.030923,-0.035095,0.016121,0.019103,0.079548
gps_height,-0.006931,0.089882,1.000000,0.139569,-0.115102,0.006069,-0.182366,-0.171162,0.114681,0.072732,0.651447
longitude,-0.005045,0.022620,0.139569,1.000000,-0.413879,0.026005,0.014463,0.140061,0.073072,0.037356,0.393988
latitude,0.004229,-0.069686,-0.115102,-0.413879,1.000000,0.010454,-0.241923,-0.183858,-0.049802,0.029844,-0.299466
num_private,-0.002469,0.002081,0.006069,0.026005,0.010454,1.000000,-0.024445,-0.007023,0.005118,0.009445,0.026991
region_code,-0.002713,-0.030923,-0.182366,0.014463,-0.241923,-0.024445,1.000000,0.706420,0.087241,-0.033835,0.024203
district_code,-0.004486,-0.035095,-0.171162,0.140061,-0.183858,-0.007023,0.706420,1.000000,0.068862,0.006955,0.063008
population,-0.004761,0.016121,0.114681,0.073072,-0.049802,0.005118,0.087241,0.068862,1.000000,0.014691,0.247425
public_meeting,0.004720,0.019103,0.072732,0.037356,0.029844,0.009445,-0.033835,0.006955,0.014691,1.000000,0.053911
construction_year,-0.004744,0.079548,0.651447,0.393988,-0.299466,0.026991,0.024203,0.063008,0.247425,0.053911,1.000000

We find that values aren't correlated to each other

In [98]:
train.columns

Index(['id', 'amount_tsh', 'date_recorded', 'funder', 'gps_height',
       'installer', 'longitude', 'latitude', 'wpt_name', 'num_private',
       'basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga',
       'ward', 'population', 'public_meeting', 'scheme_management',
       'scheme_name', 'permit', 'construction_year', 'extraction_type',
       'extraction_type_group', 'extraction_type_class', 'management',
       'management_group', 'payment_type', 'water_quality', 'quality_group',
       'quantity', 'quantity_group', 'source', 'source_type', 'source_class',
       'waterpoint_type_group', 'status_group'],
      dtype='object')

In [114]:
number = preprocessing.LabelEncoder()
train = train.astype(str)
train=train.apply(number.fit_transform)
train=train.fillna(-999)

In [115]:
Y = train.status_group
X = train.loc[:, train.columns != 'status_group']

In [119]:
kFold = model_selection.KFold(n_splits = 10, random_state = None, shuffle = True)
model = RandomForestClassifier(n_estimators=500, max_features='auto', oob_score = True, max_depth = 6)
prediction = model_selection.cross_val_score(model, X, Y, cv = kFold)

In [124]:
print(prediction)
print('Accuracy: ', prediction.mean() * 100)

[0.72831895 0.72887975 0.71901336 0.72682425 0.73299075 0.7356629
 0.74018499 0.7311408  0.74203494 0.71038027]
Accuracy:  72.95430972467051